backend/bebest/bebest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('vacancies/', include('vacancies.urls', namespace='vacancies')),
    path('export/', include('export.urls', namespace='export')),
    path('proxy/', include('log_proxy.urls', namespace='log_proxy')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'core.views.handler404'

backend/bebest/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm


app_name = 'core'


urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

backend/bebest/log_proxy/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.redirect, name='redirect'),
]

backend/bebest/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:post_id>/', views.detail, name='detail'),
]

backend/bebest/posts/models.py
import django.contrib.postgres.fields as postgres_fields
from django.db import models
from django.utils.translation import gettext_lazy as _


class Post(models.Model):
    class SourceName(models.TextChoices):
        HABR = 'habr'
        HACKERNOON = 'hackernoon'
        MEDIUM = 'medium'
        DCM = 'distributed_computing_musings'

    canonized_url = models.CharField(max_length=2048, db_index=True)
    source_name = models.CharField(max_length=128, choices=SourceName.choices)
    original_url = models.CharField(max_length=2048)
    title = models.CharField(max_length=256)
    topics = postgres_fields.ArrayField(models.CharField(max_length=256), db_index=True)
    rank = models.BigIntegerField()
    starting_text = models.TextField()
    publish_timestamp = models.BigIntegerField()
    author_username = models.CharField(max_length=128, blank=True, null=True)
    views = models.BigIntegerField(blank=True, null=True)

    def __str__(self) -> str:
        return f'Post({self.id}, canonized_url={self.canonized_url})'

    @staticmethod
    def example() -> 'Post':
        from django.utils import timezone
        return Post(
            canonized_url='https://test.com/path',
            source_name='habr',
            original_url='https://test.com/path?flag=true',
            title='MyTitle',
            topics=['development'],
            rank=1,
            starting_text='my text',
            publish_timestamp=int(timezone.now().timestamp()),
            author_username='admin',
            views=0,
        )

backend/bebest/posts/views.py
import random
from django.http import JsonResponse, HttpResponse, Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from .models import Post
from .view_models import PostView
from urllib.parse import urlparse, urlunparse

from django.forms.models import model_to_dict


def index(request):
    speciality = request.GET['speciality']
    if speciality not in ('frontend', 'backend', 'machine_learning'):
        return redirect(reverse('posts:index') + '?speciality=frontend')

    db_speciality = f'development/{speciality}'
    posts_sample = _extract_posts_sample(db_speciality)
    view_posts_sample = [PostView.from_post(post) for post in posts_sample]
    beautiful_speciality = _beautify_speciality(db_speciality)
    refresh_url = _build_refresh_url(request)
    ctx = {
        'speciality': speciality,
        'beautiful_speciality': beautiful_speciality,
        'posts': view_posts_sample,
        'refresh_url': refresh_url,
    }
    return render(request, 'posts/index.html', ctx)


def detail(request, post_id, beautify=True):
    post = get_object_or_404(Post, id=post_id)
    json_dumps_params={}
    if beautify:
        json_dumps_params={'indent': 2}
    return JsonResponse(model_to_dict(post), json_dumps_params=json_dumps_params)


def _extract_posts_sample(speciality: str):
    most_ranked_posts = list(Post.objects.filter(topics__contains=[speciality]).order_by('-rank')[:100])
    random.shuffle(most_ranked_posts)
    posts_sample = most_ranked_posts[:12]
    posts_sample.sort(key=lambda post: -post.rank)
    return posts_sample

def _beautify_speciality(speciality: str):
    match speciality:
        case 'development/frontend':
            return 'Frontend'
        case 'development/backend':
            return 'Backend'
        case 'development/machine_learning':
            return 'Machine Learning'
        case _:
            raise RuntimeError(f'Got unsupported speciality: {speciality}')

def _build_refresh_url(request) -> str:
    refresh_params = request.GET.dict()
    refresh_params.pop('box_animation', None)
    refresh_params_str = '&'.join([f'{k}={v}' for k, v in refresh_params.items()])
    return reverse('posts:index') + '?' + refresh_params_str

backend/bebest/posts/templates/posts/index.html
{% extends 'core/base.html' %}

{% block title %}BeBest - {{ beautiful_speciality }}{% endblock %}

{% block links %}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400&display=swap" rel="stylesheet">
{% endblock %}

{% block styles %}
<style>
    .post-card:hover {
        transform: scale(1.02);
    }
</style>
{% endblock %}

{% block content %}
<div class="min-h-screen {% if request.GET.box_animation %}fade-appear-fast{% endif %}">
    <div class="mt-6 px-6 py-8 rounded-xl border-2 border-rose-600/50" style="background-color: rgba(1,183,240, 0.05)">
        <div class="mb-10 lg:mb-15 mx-auto" style="height:fit-content; width:fit-content">
            <!-- <div class="mb-4 flex justify-center space-x-4 text-2xl lg:text-3xl font-sans font-bold text-orange-400">
                <div class="w-1/3 text-center">
                    <a href="{% url 'posts:index' %}?speciality=frontend" class="font-semibold hover:text-gray-500">Frontend</a>
                </div>
                <div class="w-1/3 text-center">
                    <a href="{% url 'posts:index' %}?speciality=backend" class="font-semibold hover:text-gray-500">Backend</a>
                </div>
                <div class="w-1/3 px-4">
                    <a href="{% url 'posts:index' %}?speciality=ml" class="font-semibold hover:text-gray-500">ML</a>
                </div>
            </div> -->
            <h1 class="flex justify-center mb-4">
                <a href="{{ refresh_url }}" class=" text-center text-4xl lg:text-5xl font-extrabold leading-none tracking-wide text-transparent bg-clip-text bg-gradient-to-r to-amber-300 from-red-300 hover:underline decoration-red-400/50 underline-offset-2 shadow-none transition-shadow duration-100 ease-in-out hover:shadow-lg hover:shadow-black/5">
                    Read → Learn → Create!
                </a>
            </h1>
        </div>
        <div class = "grid sm:grid-cols-1 md:grid-cols-3 gap-y-4 gap-x-4 fade-appear-fast">
            {% for post in posts %}
                <!-- <a href="{% url 'log_proxy:redirect' %}?next={{ post.canonized_url|urlencode }}" target="_blank"> -->
                <a href="{{ post.canonized_url }}" target="_blank">
                    <div class="post-card h-40 p-4 pb-3 lg:p-6 lg:pb-6 border border-slate-100 bg-white rounded-xl shadow-none transition-shadow duration-100 ease-in-out hover:shadow-lg hover:shadow-black/5">
                        <div class="h-3/4 w-full flex items-center justify-center">
                            <h2 class="text-lg lg:text-xl text-center line-clamp-3" style="font-family: 'Roboto', sans-serif; font-weight: 300;">{{ post.title }}</h2>
                        </div>
                        <div class="h-1/4 w-full align-middle">
                            <p class="text-md lg:text-lg text-center font-normal text-gray-400" style="position: relative; bottom: 1%;">
                                {% if post.has_author %}
                                    {{ post.beautiful_source_name }} &centerdot; {{ post.author_username }}
                                {% else %}
                                    {{ post.beautiful_source_name }}
                                {% endif %}
                            </p>
                        </div>
                    </div>
                </a>
            {% endfor %}
        </div>
    </div>
</div>
<script>
    document.addEventListener("DOMContentLoaded", function(event) { 
        var scrollpos = localStorage.getItem('scrollpos');
        if (scrollpos) window.scrollTo(0, scrollpos);
    });

    window.onbeforeunload = function(e) {
        localStorage.setItem('scrollpos', window.scrollY);
    };
</script>
{% endblock %}