backend/bebest/bebest/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('core.urls', namespace='core')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('vacancies/', include('vacancies.urls', namespace='vacancies')),
    path('export/', include('export.urls', namespace='export')),
    path('proxy/', include('log_proxy.urls', namespace='log_proxy')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'core.views.handler404'

backend/bebest/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views
from .forms import LoginForm


app_name = 'core'


urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

backend/bebest/core/models.py
from django.db import models


class Language(models.Model):
    ENGLISH = 'en'
    RUSSIAN = 'ru'
    ID_CHOICES = [
        (ENGLISH, 'English'),
        (RUSSIAN, 'Russian'),
    ]

    id = models.CharField(primary_key=True, max_length=3, choices=ID_CHOICES)

backend/bebest/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'The Boss',
        'class': 'w-full py-2 px-2 rounded-xl',
    }))
    email = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'elon_musk@mars.com',
        'class': 'w-full py-2 px-2 rounded-xl',
    }))
    password1 = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'w-full py-2 px-2 rounded-xl',
    }))
    password2 = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'w-full py-2 px-2 rounded-xl',
    }))


class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'The Boss',
        'class': 'w-full py-2 px-2 rounded-xl',
    }))
    password = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'w-full py-2 px-2 rounded-xl',
    }))

backend/bebest/core/views.py
import logging
import traceback
import django.contrib.auth as auth
from django.contrib import messages
from django.shortcuts import render, redirect
from posts.models import Post

from .forms import SignupForm, LoginForm


def index(request):
    return render(request, 'core/index.html')


def contact(request):
    return render(request, 'core/contact.html')


def signup(request):
    form = SignupForm(request.POST or None)
    if request.method == 'POST' and form.is_valid():
        form.save()
        new_user = auth.authenticate(username=form.cleaned_data['username'],
                                password=form.cleaned_data['password1'])
        auth.login(request, new_user)
        if 'next' in request.POST:
            return redirect(request.POST.get('next'))
        return redirect('/')

    return render(request, 'core/signup.html', dict(form=form, query_string=request.META['QUERY_STRING']))


def login(request):
    form = LoginForm(request.POST or None)
    if request.method == 'POST':
        user = auth.authenticate(
            request,
            username=request.POST.get('username'),
            password=request.POST.get('password'),
        )
        if user is not None:
            auth.login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            return redirect('/')
        else:
            form.errors['password'] = 'Invalid username or password'
    return render(request, 'core/login.html', dict(form=form))


def logout(request):
    auth.logout(request)
    if request.method == 'GET' and 'next' in request.GET:
        return redirect(request.GET.get('next'))
    return redirect('/')


def handler404(request, exception):
    logging.error(f'404 on {request.build_absolute_uri()}. Error: {exception}')
    return render(request, 'core/404.html', {})

backend/bebest/core/templates/core/base.html
{% load static %}
{% load utils %}
<!DOCTYPE html>

<html lang="en-us">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'core/style.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'core/underline.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'core/wave_background.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'core/get_started_button.css' %}">
        {% block links %}
        {% endblock %}

        <style>

        </style>
        {% block styles %}
        {% endblock %}

        <title>{% block title %}{% endblock %}</title>
        <link rel="icon" type="image/x-icon" href="{% static 'core/favicon.ico' %}">
    </head>
    <body>
        <div class="flex flex-col">
        <nav class="py-6 px-6 flex flex-wrap gap-4 justify-between items-center border-b border-gray-200">
            <a href="/" class="text-2xl font-semibold">
                <span class="hover-underline-animation text-transparent bg-clip-text bg-gradient-to-t to-orange-400 from-red-400">
                    Be the Best
                </span>
            </a>
            <!-- exp: {% if request.user.is_authenticated %}mr-6{% endif %} -->
            <div class="space-x-4 sm:space-x-4 lg:space-x-6 text-md sm:text-md lg:text-lg mr-5">

                <a href="{% url 'posts:index' %}?speciality=frontend&box_animation=true" class="font-semibold hover:text-violet-500 {% if speciality == 'frontend' %}underline underline-offset-2 text-violet-700{% endif %}">Frontend</a>
                <a href="{% url 'posts:index' %}?speciality=backend&box_animation=true" class="font-semibold hover:text-violet-500 {% if speciality == 'backend' %}underline underline-offset-2 text-violet-700{% endif %}">Backend</a>
                <a href="{% url 'posts:index' %}?speciality=machine_learning&box_animation=true" class="font-semibold hover:text-violet-500 {% if speciality == 'machine_learning' %}underline underline-offset-2 text-violet-700{% endif %}">ML</a>
                <!-- <a href="{% url 'vacancies:index' %}?box_animation=true" class="font-semibold hover:text-gray-500">Vacancies</a> -->

                {% if request.user.is_authenticated %}
                {% else %}
                    <!-- <a href="{% url 'core:signup' %}{% if not request.path|startswith:'/signup' %}?next={{ request.get_full_path|urlencode }}{% elif request.GET.next is not None %}?next={{ request.GET.next }}{% endif %}" class="px-6 py-3 font-semibold bg-amber-300 text-white rounded-xl hover:bg-yellow-500 whitespace-nowrap">Sign up</a> -->
                    <!-- <a href="{% url 'core:login' %}{% if not request.path|startswith:'/login' %}?next={{ request.get_full_path|urlencode }}{% elif request.GET.next is not None %}?next={{ request.GET.next }}{% endif %}" class="px-6 py-3 font-semibold text-white rounded-xl hover:bg-gray-700 whitespace-nowrap" style="background-color: rgba(1,183,240, 1.0)">Log in</a> -->
                {% endif %}
            </div>
        </nav>
        <div class="px-6 py-6 flex flex-col">
            {% block content %}
            {% endblock %}
        </div>
        <footer class="py-6 px-6 flex justify-between bg-gray-800"">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>
                <div class="w-1/3">
                    <p class="text-lg text-gray-500">This website was developed by Dmitriy Brusenin. You can find more about me on the <u><a href="{% url 'core:contact' %}">contact</a></u> page.</p>
                </div>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
                <ul class="space-y-2">
                    <li><a href="{% url 'core:index' %}" class="text-lg text-sky-400 hover:text-violet-500">Home</a></li>
                    <li><a href="{% url 'core:contact' %}" class="text-lg text-sky-400 hover:text-violet-500">Contact</a></li>
                    <li><a href="#" class="text-lg text-sky-400 hover:text-violet-500">Privacy policy</a></li>
                </ul>
            </div>
        </footer>
        </div>
    </body>
</html>

backend/bebest/core/templates/core/contact.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %}BeBest — Contact{% endblock %}

{% block content %}
<div class="min-h-screen">
    <div class="text-4xl md:text-5xl lg:text-6xl mt-10 flex justify-center">
        <a href="https://dbrusenin.com" target="_blank">
            <img src="{% static 'core/dbrusenin_ava.png' %}" width="320" alt="Dmitriy Brusenin" class="clickable-image-with-border" style="border-radius: 50%; object-fit: cover;">
        </a>
    </div>

    <div class="text-4xl md:text-5xl lg:text-6xl ml-2 mt-10 flex justify-center">
        <a href="https://github.com/Deimvis" target="_blank">
            <img src="{% static 'core/github_logo.png' %}" width="320" alt="GitHub" class="clickable-image">
        </a>
    </div>
    <!-- <div class="text-3xl md:text-4xl lg:text-5xl mt-2 flex justify-center">
        <a href="https://github.com/Deimvis" target="_blank" class="text-blue-600 dark:text-blue-500 hover:underline decoration-3">Deimvis</a>
    </div> -->
    <div class="text-4xl md:text-5xl lg:text-6xl ml-2 mt-10 flex justify-center">
        <a href="https://www.linkedin.com/in/dmitriy-brusenin-637715225/" target="_blank">
            <img src="{% static 'core/linkedin_logo.png' %}" width="320" alt="GitHub" class="clickable-image">
        </a>
    </div>
    <!-- <div class="text-3xl md:text-4xl lg:text-5xl mt-4 flex justify-center">
        <a href="https://www.linkedin.com/in/dmitriy-brusenin-637715225/" target="_blank" class="text-blue-600 dark:text-blue-500 hover:underline decoration-3">Dmitriy Brusenin</a>
    </div> -->
</div>
{% endblock %}

backend/bebest/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}BeBest{% endblock %}

{% block content %}
<div class="h-screen">
<div class="mt-6 px-6 py-12 rounded-xl items-center" style="text-align: center">
    <h1 class="text-center mb-4 text-4xl font-extrabold leading-none tracking-tight text-transparent bg-clip-text bg-gradient-to-r to-amber-300 from-red-300 md:text-5xl lg:text-6xl">
        Welcome
    </h1>
    <div style="display: inline-block">
      <div class="mb-6 text-lg font-normal text-gray-500 lg:text-xl dark:text-gray-400 typewriter">
        Here at BeBest we help IT professionals striving for 
        <span class="underline decoration-3 decoration-amber-500">best practices</span>,
        <span class="underline decoration-3 decoration-amber-500">perfection</span>, and 
        <span class="underline decoration-3 decoration-amber-500">success</span>
      </div>
    </div>
    <br>
    <br>
    <br>
    <div class="flex items-center justify-center delayed-fade-appear-normal-after-3s">
    <a class="cta" href="{% url 'posts:index' %}?speciality=backend&box_animation=true">
        <span class="px-3 font-extrabold">GET STARTED</span>
        <span class="flex items-center justify-center">
          <svg width="66px" height="43px" viewBox="0 0 66 43" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
            <g id="arrow" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd" class="flex justify-content: center align-items: center box-sizing: border-box">
              <path class="one" d="M40.1543933,3.89485454 L43.9763149,0.139296592 C44.1708311,-0.0518420739 44.4826329,-0.0518571125 44.6771675,0.139262789 L65.6916134,20.7848311 C66.0855801,21.1718824 66.0911863,21.8050225 65.704135,22.1989893 C65.7000188,22.2031791 65.6958657,22.2073326 65.6916762,22.2114492 L44.677098,42.8607841 C44.4825957,43.0519059 44.1708242,43.0519358 43.9762853,42.8608513 L40.1545186,39.1069479 C39.9575152,38.9134427 39.9546793,38.5968729 40.1481845,38.3998695 C40.1502893,38.3977268 40.1524132,38.395603 40.1545562,38.3934985 L56.9937789,21.8567812 C57.1908028,21.6632968 57.193672,21.3467273 57.0001876,21.1497035 C56.9980647,21.1475418 56.9959223,21.1453995 56.9937605,21.1432767 L40.1545208,4.60825197 C39.9574869,4.41477773 39.9546013,4.09820839 40.1480756,3.90117456 C40.1501626,3.89904911 40.1522686,3.89694235 40.1543933,3.89485454 Z" fill="#FFFFFF"></path>
              <path class="two" d="M20.1543933,3.89485454 L23.9763149,0.139296592 C24.1708311,-0.0518420739 24.4826329,-0.0518571125 24.6771675,0.139262789 L45.6916134,20.7848311 C46.0855801,21.1718824 46.0911863,21.8050225 45.704135,22.1989893 C45.7000188,22.2031791 45.6958657,22.2073326 45.6916762,22.2114492 L24.677098,42.8607841 C24.4825957,43.0519059 24.1708242,43.0519358 23.9762853,42.8608513 L20.1545186,39.1069479 C19.9575152,38.9134427 19.9546793,38.5968729 20.1481845,38.3998695 C20.1502893,38.3977268 20.1524132,38.395603 20.1545562,38.3934985 L36.9937789,21.8567812 C37.1908028,21.6632968 37.193672,21.3467273 37.0001876,21.1497035 C36.9980647,21.1475418 36.9959223,21.1453995 36.9937605,21.1432767 L20.1545208,4.60825197 C19.9574869,4.41477773 19.9546013,4.09820839 20.1480756,3.90117456 C20.1501626,3.89904911 20.1522686,3.89694235 20.1543933,3.89485454 Z" fill="#FFFFFF"></path>
              <path class="three" d="M0.154393339,3.89485454 L3.97631488,0.139296592 C4.17083111,-0.0518420739 4.48263286,-0.0518571125 4.67716753,0.139262789 L25.6916134,20.7848311 C26.0855801,21.1718824 26.0911863,21.8050225 25.704135,22.1989893 C25.7000188,22.2031791 25.6958657,22.2073326 25.6916762,22.2114492 L4.67709797,42.8607841 C4.48259567,43.0519059 4.17082418,43.0519358 3.97628526,42.8608513 L0.154518591,39.1069479 C-0.0424848215,38.9134427 -0.0453206733,38.5968729 0.148184538,38.3998695 C0.150289256,38.3977268 0.152413239,38.395603 0.154556228,38.3934985 L16.9937789,21.8567812 C17.1908028,21.6632968 17.193672,21.3467273 17.0001876,21.1497035 C16.9980647,21.1475418 16.9959223,21.1453995 16.9937605,21.1432767 L0.15452076,4.60825197 C-0.0425130651,4.41477773 -0.0453986756,4.09820839 0.148075568,3.90117456 C0.150162624,3.89904911 0.152268631,3.89694235 0.154393339,3.89485454 Z" fill="#FFFFFF"></path>
            </g>
          </svg>
        </span>
      </a>
      </div>
</div>
</div>
{% endblock %}

backend/bebest/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-2/3 lg:w-1/3 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>
    <form method="post" action=".">
        {% csrf_token %}
        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
            </div>
        {% endif %}
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}

backend/bebest/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-2/3 lg:w-1/3 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>
    <form method="post" action="?{{ query_string }}">
        {% csrf_token %}
        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
            </div>
        {% endif %}

        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        {% if request.POST.next %}
            <input type="hidden" name="next" value="{{ request.POST.next }}">
        {% endif %}
        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>
{% endblock %}